### ISSUE TITLE
CredentialsWarning on HeliumSettings.GetAndroidAppSignature

### ISSUE THREAD

**Issue by vyury** [ChartBoost/helium-unity-sdk#60]
HeliumSettings.GetAndroidAppSignature()

        public static string GetAndroidAppSignature()
        {
            switch (Instance.androidAppSignature)
            {
                case AndroidExampleAppSignature:
                    CredentialsWarning(CredentialsWarningDefaultFormat, CredentialsWarningAndroid, CredentialsWarningAppSignature);

                    return IOSExampleAppSignature;
                default:
                    CredentialsWarning(CredentialsWarningEmptyFormat, CredentialsWarningAndroid, CredentialsWarningAppSignature);
                    // use it anyway
                    break;
            }
            return Instance.androidAppSignature;
        }

You are always Logging CredentialsWarning. 
This is only needed if the string is empty.

**Comment by SCastanedaMunoz** [comment]
Hey @vyury, there is an issue here on what value is actually returned if using the Sample App Signature or an Empty String as the app signature, That will be corrected. However, this logging is meant to be in place always! As it is meant to notify you when you have a bad configuration for Helium. You need to replace the values in your HeliumSettings, or utilize the available API to pass your own AppID, and AppSignature for Android/iOS. Once that happens this logging should disappear. Let me know if that helps.

**Comment by vyury** [comment]
Hey @SCastanedaMunoz. Please look to your methods.  GetAndroidAppId works correct 

        public static string GetAndroidAppId()
        {
            switch (Instance.androidAppId)
            {
                case AndroidExampleAppID:
                    CredentialsWarning(CredentialsWarningDefaultFormat, CredentialsWarningAndroid, CredentialsWarningAppID);
                    return AndroidExampleAppID;
                case "":
                    CredentialsWarning(CredentialsWarningEmptyFormat, CredentialsWarningAndroid, CredentialsWarningAppID);
                    // use it anyway
                    break;
            }
            return Instance.androidAppId;
        }

But in GetAndroidAppSignature() you use "default:" instead of "" (empty string)

        public static string GetAndroidAppSignature()
        {
            switch (Instance.androidAppSignature)
            {
                case AndroidExampleAppSignature:
                    CredentialsWarning(CredentialsWarningDefaultFormat, CredentialsWarningAndroid, CredentialsWarningAppSignature);

                    return IOSExampleAppSignature;
                default:
                    CredentialsWarning(CredentialsWarningEmptyFormat, CredentialsWarningAndroid, CredentialsWarningAppSignature);
                    // use it anyway
                    break;
            }
            return Instance.androidAppSignature;
        }

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements

The default case can appear in any place within a switch statement. Regardless of its position, the default case is always evaluated last and only if all other case patterns aren't matched.
