### ISSUE TITLE
NullRef after initialization from HeliumEventProcessor

### ISSUE THREAD

**Issue by vyury** [ChartBoost/helium-unity-sdk#61]
**Helium Integration (please complete the following information):**
 - Helium SDK version: 3.2.0
 - Platform:  Android
 - Unity version: 2021.3.12f1

When HeliumEventProcessor invokes from java code by reflection static constructor of the HeliumEventProcessor not invokes.

        public static void ProcessHeliumEvent(int errorCode, string errorDescription, HeliumEvent heliumEvent)
        {
            _context.Post(o =>
            {

_context is null

<img width="1019" alt="img2" src="https://user-images.githubusercontent.com/6699588/199534263-93c43846-576b-411e-ab7d-7f14242cf353.png">

**Comment by SCastanedaMunoz** [comment]
@vyury Can you provide more information on how your current setup looks like? As you mentioned, this seems to be happening right after initialization, having more information on your integration will be of great help to figure out what could be the culprit behind this NullRef

**Comment by vyury** [comment]
My initialization:
        
       public void Initialize(IList<PlacementData> placements)
        {
            Subscribe();
            Placements = placements;
            
            LogMessage("Helium Start");

#if UNITY_ANDROID
            var appID = HeliumSettings.GetAndroidAppId();
            var appSignature = HeliumSettings.GetAndroidAppSignature();
#elif UNITY_IOS
            var appID = HeliumSettings.GetIOSAppId();
            var appSignature = HeliumSettings.GetIOSAppSignature();
#endif

            HeliumSDK.StartWithAppIdAndAppSignature(appID, appSignature);

**Comment by vyury** [comment]
Workaround to remove NullRef:
           
#if UNITY_ANDROID
            var appID = HeliumSettings.GetAndroidAppId();
            var appSignature = HeliumSettings.GetAndroidAppSignature();
#elif UNITY_IOS
            var appID = HeliumSettings.GetIOSAppId();
            var appSignature = HeliumSettings.GetIOSAppSignature();
#endif
            //need this subscription to invoke HeliumEventProcessor static constructor
            HeliumEventProcessor.UnexpectedSystemErrorDidOccur += HeliumEventProcessor_UnexpectedSystemErrorDidOccur;

            HeliumSDK.StartWithAppIdAndAppSignature(appID, appSignature);

**Comment by SCastanedaMunoz** [comment]
@vyury Thanks for providing reproductions steps, I will take a look and get back to you soon.

**Comment by SCastanedaMunoz** [comment]
@vyury  a PR has been made to avoid this issue in the future 👍🏻 this will be added for the 3.3.0 release.
